version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./cmd/todo/Dockerfile.local
    command: "air -c /app/cmd/todo/.air.toml"
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    env_file:
      - ./cmd/todo/.env.local
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: todo-user
      POSTGRES_PASSWORD: todo-password
      POSTGRES_DB: todos
    restart: always
