FROM golang:1.21-alpine

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./
COPY cmd/todo/.air.toml .air.toml
RUN go mod download
COPY . .
# CMD ["air", "-c", ".air.toml"]